import { chromium } from 'playwright';
const BASE_URL = process.argv[2] || 'http://localhost:3418';
const browser = await chromium.launch();
console.log('t0', Date.now());
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' });
console.log('context created', Date.now());
const page = await context.newPage();
console.log('page created', Date.now());
page.setDefaultTimeout(15000);
await page.goto(BASE_URL, { waitUntil: 'load' });
console.log('goto done', Date.now());
await page.waitForTimeout(1500);
console.log('wait done', Date.now());
const size = await page.evaluate(() => { const c = document.querySelector('canvas'); return c ? {w:c.width,h:c.height} : null; });
console.log('canvas size', size, Date.now());
const flag = await page.evaluate(() => window.__NEXORA_REDUCED_MOTION__ ?? null);
console.log('reduced motion flag', flag, Date.now());
await context.close();
console.log('context closed', Date.now());
await browser.close();
console.log('browser closed', Date.now());
