import { chromium } from 'playwright';
const BASE_URL = process.argv[2] || 'http://localhost:3418';
const t0 = Date.now();
const log = (m) => console.log(`[+${Date.now()-t0}ms] ${m}`);
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, reducedMotion: 'reduce' });
const page = await context.newPage();
page.setDefaultTimeout(15000);
await page.goto(BASE_URL, { waitUntil: 'load' });
log('goto done');
await page.waitForTimeout(1500);
log('wait done');
const flag = await page.evaluate(() => window.__NEXORA_REDUCED_MOTION__ ?? null);
log(`flag=${flag}`);
log('about to screenshot');
await page.screenshot({ path: 'verification/diag4-reduced-motion.png' });
log('screenshot done');
await browser.close();
log('browser closed');
